### ISSUE TITLE
Question: statd implementation compatibility

### ISSUE THREAD

**Issue by jeekajoo** [coursera/metrics-datadog#80]
Hello,

If tomorrow I want to stop using datadog, I'd like to know if `metrics-datadog` would be working with the pristine statd implementation (so without tags: https://docs.datadoghq.com/guides/dogstatsd/#tags).

I'm asking this because I'm looking at datadog, but I want to be sure I can move somewhere else, after, by 
still benefiting from the statd **protocol**.

[Edit] A better wording would be, can we send metrics without tags (in case the server doesn't support it)

Thanks much! :)

**Comment by nickdella** [comment]
Hi @jeekajoo ! This is probably a question better answered by the Datadog team. They says dogstatsd extends statsd and there are mentions of backward compatibility in the doc you linked to, but I've never tried sending dogstatsd to a statsd server myself

If it turns out that dogstatsd and statsd are incompatible, it would be pretty easy to swap out this `metrics-datadog` reporter for a [statsd reporter](https://github.com/ReadyTalk/metrics-statsd) .  Though, because tagging is not natively supported in Metrics v3.x ([coming in v4](https://github.com/dropwizard/metrics/issues/877)), you'll need a lightweight layer to handle [encoding tags into metric names](https://github.com/coursera/metrics-datadog#tag-encoding-and-expansion). This layer would need to disable/ignore tags when tracking metrics.

Hope all this makes sense :)

**Comment by jeekajoo** [comment]
It makes sense, thank you! I didn't know https://github.com/ReadyTalk/metrics-statsd.
